default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#Feel Free to change the username and password to match your local postgres env
development:
  <<: *default
  database: p3_dev
  username: test3
  password: test3
  port: 5432
  host: localhost

#Feel Free to change the username and password to match your local postgres env
test:
  <<: *default
  database: p3_test
  username: test3
  password: test3
  port: 5432
  host: localhost


production:
  <<: *default
  database: p3_production
  url: <%= ENV['DATABASE_URL'] %>